// Generated by the gRPC C++ plugin.
// If you make any local change, they will be lost.
// source: Coordinator_RPC.proto

#include "Coordinator_RPC.pb.h"
#include "Coordinator_RPC.grpc.pb.h"

#include <functional>
#include <grpcpp/support/async_stream.h>
#include <grpcpp/support/async_unary_call.h>
#include <grpcpp/impl/channel_interface.h>
#include <grpcpp/impl/client_unary_call.h>
#include <grpcpp/support/client_callback.h>
#include <grpcpp/support/message_allocator.h>
#include <grpcpp/support/method_handler.h>
#include <grpcpp/impl/rpc_service_method.h>
#include <grpcpp/support/server_callback.h>
#include <grpcpp/impl/server_callback_handlers.h>
#include <grpcpp/server_context.h>
#include <grpcpp/impl/service_type.h>
#include <grpcpp/support/sync_stream.h>

static const char* Contact_method_names[] = {
  "/Contact/ContactCoordinator",
};

std::unique_ptr< Contact::Stub> Contact::NewStub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options) {
  (void)options;
  std::unique_ptr< Contact::Stub> stub(new Contact::Stub(channel, options));
  return stub;
}

Contact::Stub::Stub(const std::shared_ptr< ::grpc::ChannelInterface>& channel, const ::grpc::StubOptions& options)
  : channel_(channel), rpcmethod_ContactCoordinator_(Contact_method_names[0], options.suffix_for_stats(),::grpc::internal::RpcMethod::NORMAL_RPC, channel)
  {}

::grpc::Status Contact::Stub::ContactCoordinator(::grpc::ClientContext* context, const ::Request& request, ::Reply* response) {
  return ::grpc::internal::BlockingUnaryCall< ::Request, ::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), rpcmethod_ContactCoordinator_, context, request, response);
}

void Contact::Stub::async::ContactCoordinator(::grpc::ClientContext* context, const ::Request* request, ::Reply* response, std::function<void(::grpc::Status)> f) {
  ::grpc::internal::CallbackUnaryCall< ::Request, ::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ContactCoordinator_, context, request, response, std::move(f));
}

void Contact::Stub::async::ContactCoordinator(::grpc::ClientContext* context, const ::Request* request, ::Reply* response, ::grpc::ClientUnaryReactor* reactor) {
  ::grpc::internal::ClientCallbackUnaryFactory::Create< ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(stub_->channel_.get(), stub_->rpcmethod_ContactCoordinator_, context, request, response, reactor);
}

::grpc::ClientAsyncResponseReader< ::Reply>* Contact::Stub::PrepareAsyncContactCoordinatorRaw(::grpc::ClientContext* context, const ::Request& request, ::grpc::CompletionQueue* cq) {
  return ::grpc::internal::ClientAsyncResponseReaderHelper::Create< ::Reply, ::Request, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(channel_.get(), cq, rpcmethod_ContactCoordinator_, context, request);
}

::grpc::ClientAsyncResponseReader< ::Reply>* Contact::Stub::AsyncContactCoordinatorRaw(::grpc::ClientContext* context, const ::Request& request, ::grpc::CompletionQueue* cq) {
  auto* result =
    this->PrepareAsyncContactCoordinatorRaw(context, request, cq);
  result->StartCall();
  return result;
}

Contact::Service::Service() {
  AddMethod(new ::grpc::internal::RpcServiceMethod(
      Contact_method_names[0],
      ::grpc::internal::RpcMethod::NORMAL_RPC,
      new ::grpc::internal::RpcMethodHandler< Contact::Service, ::Request, ::Reply, ::grpc::protobuf::MessageLite, ::grpc::protobuf::MessageLite>(
          [](Contact::Service* service,
             ::grpc::ServerContext* ctx,
             const ::Request* req,
             ::Reply* resp) {
               return service->ContactCoordinator(ctx, req, resp);
             }, this)));
}

Contact::Service::~Service() {
}

::grpc::Status Contact::Service::ContactCoordinator(::grpc::ServerContext* context, const ::Request* request, ::Reply* response) {
  (void) context;
  (void) request;
  (void) response;
  return ::grpc::Status(::grpc::StatusCode::UNIMPLEMENTED, "");
}


